Merge slovdahl to moimael
moimael/trac-to-gitlab pull request #16
Opened 2017-02-07 20:41 UTC by jfkw

Please pull to integrate @slovdahl changes into moimael master. Commits created by cherry-pick of individual commits from slovdahl/master after common ancestor. No changes made to @slovdahl commits other than merge conflict resolution.

2017-02-09 15:59 UTC, moimael requested changes

2017-02-09 15:59 UTC, moimael commented on migrate.py
> +reload(sys)
I'm not super fond of this:

http://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

2017-02-09 16:37 UTC, slovdahl commented
I had no intention of getting this merged upstream myself, it's just a collection of random stuff I had to change/fix to make the script work for our specific migration.

2017-02-09 16:40 UTC, slovdahl commented
Would it be a better idea to submit a few separate pull requests with specific changes? GitLab 8.15 database scheme, improved trac wiki syntax conversion, etc.

2017-02-09 16:40 UTC, moimael commented
Yes I understand, it's an issue with this kind of project, it's used once so nobody want to maintain it. I guess I can accept the PR and if someone want to clean it up, he can do it.

2017-02-09 16:41 UTC, moimael commented
Yes maybe separate PR would be better, but does your changes still work without the utf8 hack ?

2017-02-09 16:43 UTC, slovdahl commented
The utf8 hack was needed to migrate some ticket descriptions and comments that contained obscure characters, so I think generally, yes, it should work without it.

2017-02-09 16:57 UTC, jfkw commented
@slovdahl apologies if I brought over commits you didn't intend. I went to look for git private messaging to check with you first about it, but they've removed that channel.

I added a commit to revert setdefaultencoding('utf-8').

@slovdahl I left in the encoding argument to xmlrpc.ServerProxy(encoding='utf-8'), is this sufficient to handle the special characters you encountered?

2017-02-09 17:01 UTC, slovdahl commented
@jfkw No need to apologise! If I didn't want to risk this I wouldn't have made it public on GitHub at all :) Just didn't intend to do it myself.

I'm cleaning up the repo a little bit at the moment and will submit separate pull requests for at least some of the issues.

I'm unsure about the utf8 issue and I'm unfortunately not able to verify it at the moment either.

2017-02-09 23:09 UTC, jfkw commented
Don't mind my updates to the PR branch. It sounds like @slovdahl is going to submit mulitple PRs to merge changes. I'm just trying to keep my branch in a merge-ready state while I move forward.

2017-02-10 15:11 UTC, slovdahl commented
@jfkw would you mind rebasing this branch on top of the current master and check if there's anything else you're interested in having merged upstream? I'd be happy to submit further pull requests in that case.

2017-02-10 16:22 UTC, jfkw commented
@slovdahl Yes, I'll redo the branch based on current head.

2017-04-20 10:29 UTC, closed without merging